"""add customer address and require phone

Revision ID: eaf0da1d7a46
Revises: c5d7ffd73b95
Create Date: 2026-09-20 23:27:09.879656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf0da1d7a46'
down_revision: Union[str, Sequence[str], None] = 'c5d7ffd73b95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('address', sa.String(length=255), nullable=False))
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.alter_column('customers', 'phone',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('customers', 'address')
    # ### end Alembic commands ###
